services:
  - type: web
    name: urfu-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    autoDeploy: true
    healthCheckPath: /
    pullRequestPreviewsEnabled: false

